//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTM.HTMBitmapProcessor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDB() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTM.HTMBitmapProcessor.ResourceDB", typeof(ResourceDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 15 ähnelt.
        /// </summary>
        internal static string ContextMaxVocab {
            get {
                return ResourceManager.GetString("ContextMaxVocab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 11 ähnelt.
        /// </summary>
        internal static string ContextSentenceLength {
            get {
                return ResourceManager.GetString("ContextSentenceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die data source=HOLM\SQLEXPRESS;initial catalog=Log;integrated security=true ähnelt.
        /// </summary>
        internal static string dbConnString {
            get {
                return ResourceManager.GetString("dbConnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Into Log.dbo.AppContextElements (Element) Values ähnelt.
        /// </summary>
        internal static string dbInsertAppContextElements {
            get {
                return ResourceManager.GetString("dbInsertAppContextElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string dbLastReadTimeStamp {
            get {
                return ResourceManager.GetString("dbLastReadTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @TimeStamp ähnelt.
        /// </summary>
        internal static string dbLastReadTimeStampParam {
            get {
                return ResourceManager.GetString("dbLastReadTimeStampParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System.Data.SqlClient ähnelt.
        /// </summary>
        internal static string dbProvider {
            get {
                return ResourceManager.GetString("dbProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select * FROM Log.dbo.AppContextElements ähnelt.
        /// </summary>
        internal static string dbSelectAppContextElements {
            get {
                return ResourceManager.GetString("dbSelectAppContextElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT TOP 1 TimeStamp, Element, Ancestor1, Ancestor2, Ancestor3, Ancestor4 From Log.dbo.UILog ähnelt.
        /// </summary>
        internal static string dbSelectUILogEvents {
            get {
                return ResourceManager.GetString("dbSelectUILogEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element ähnelt.
        /// </summary>
        internal static string UILogField1 {
            get {
                return ResourceManager.GetString("UILogField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancestor1 ähnelt.
        /// </summary>
        internal static string UILogField2 {
            get {
                return ResourceManager.GetString("UILogField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancestor2 ähnelt.
        /// </summary>
        internal static string UILogField3 {
            get {
                return ResourceManager.GetString("UILogField3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancestor3 ähnelt.
        /// </summary>
        internal static string UILogField4 {
            get {
                return ResourceManager.GetString("UILogField4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancestor4 ähnelt.
        /// </summary>
        internal static string UILogField5 {
            get {
                return ResourceManager.GetString("UILogField5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5 ähnelt.
        /// </summary>
        internal static string UILogFieldLength {
            get {
                return ResourceManager.GetString("UILogFieldLength", resourceCulture);
            }
        }
    }
}
