//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.261
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTM.UIHtmCal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enable this Region for input processing (Region is created fresh if parameters ha" +
            "ve changed since last on).")]
        public string ToolTipRegionCheck {
            get {
                return ((string)(this["ToolTipRegionCheck"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Percent of input bits within locality radius each Column has potential (proximal)" +
            " synapses for.")]
        public string ToolTipPerColText {
            get {
                return ((string)(this["ToolTipPerColText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Furthest number of Columns away to allow distal synapse connections (0 means no r" +
            "estriction).")]
        public string ToolTipLocalityRadText {
            get {
                return ((string)(this["ToolTipLocalityRadText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimum percent of column\'s proximal synapses that must be active for the column " +
            "to be considered by the spatial pooler.")]
        public string ToolTipMinOverlapText {
            get {
                return ((string)(this["ToolTipMinOverlapText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Approximate percent of Columns within locality radius to be winners after inhibit" +
            "ion.")]
        public string ToolTipDesireLocalText {
            get {
                return ((string)(this["ToolTipDesireLocalText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Number of (temporal context) cells to use for each Column.")]
        public string ToolTipCellsPerColText {
            get {
                return ((string)(this["ToolTipCellsPerColText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimum number of active synapses to activate a segment.")]
        public string ToolTipThresholdText {
            get {
                return ((string)(this["ToolTipThresholdText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Number of \'new\' synapses to add to a segment if none activated during learning.")]
        public string ToolTipNewSynapsesText {
            get {
                return ((string)(this["ToolTipNewSynapsesText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Number of Columns in the X direction (width) in this Region.")]
        public string ToolTipColXText {
            get {
                return ((string)(this["ToolTipColXText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Number of Columns in the Y direction (height) in this Region.")]
        public string ToolTipColYText {
            get {
                return ((string)(this["ToolTipColYText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Radius, in Columns, of how far inhibition will take effect per Column (most recen" +
            "t time step).")]
        public string ToolTipInhiRadText {
            get {
                return ((string)(this["ToolTipInhiRadText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correctly predicted active columns out of total sequence-segment predicted column" +
            "s (most recent time step).")]
        public string ToolTipPredAccText {
            get {
                return ((string)(this["ToolTipPredAccText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Correctly predicated active columns out of total active columns (most recent time" +
            " step).")]
        public string ToolTipActiveAccText {
            get {
                return ((string)(this["ToolTipActiveAccText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current state of the Region.")]
        public string ToolTipRegionStatusText {
            get {
                return ((string)(this["ToolTipRegionStatusText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVE\\SQLEXPRESS;Initial Catalog=ContextLexikon;Integrated Security=Tr" +
            "ue")]
        public string ContextLexikonConnectionString {
            get {
                return ((string)(this["ContextLexikonConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string MaxNumberHTMRegions {
            get {
                return ((string)(this["MaxNumberHTMRegions"]));
            }
            set {
                this["MaxNumberHTMRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please Be A Fine Girl Kiss Me")]
        public string ListBoxSentence1 {
            get {
                return ((string)(this["ListBoxSentence1"]));
            }
            set {
                this["ListBoxSentence1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inside Crystal Mountain Evil Takes its Form")]
        public string ListBoxSentence2 {
            get {
                return ((string)(this["ListBoxSentence2"]));
            }
            set {
                this["ListBoxSentence2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Our so called leaders speak with words they try to jail you")]
        public string ListBoxSentence3 {
            get {
                return ((string)(this["ListBoxSentence3"]));
            }
            set {
                this["ListBoxSentence3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The power of now is the absence of longing")]
        public string ListBoxSentence4 {
            get {
                return ((string)(this["ListBoxSentence4"]));
            }
            set {
                this["ListBoxSentence4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sliderNoise")]
        public string SliderNoise {
            get {
                return ((string)(this["SliderNoise"]));
            }
            set {
                this["SliderNoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sliderLetters")]
        public string SliderLetters {
            get {
                return ((string)(this["SliderLetters"]));
            }
            set {
                this["SliderLetters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COZYLUMMOXGIVESSMARTSQUIDWHOASKSFORJOBPEN")]
        public string ListBoxSentence5 {
            get {
                return ((string)(this["ListBoxSentence5"]));
            }
            set {
                this["ListBoxSentence5"] = value;
            }
        }
    }
}
